name: Update Forks

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Personal Access Token'
        required: true
      username:
        description: 'GitHub Username'
        required: true

jobs:
  update-forks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Update Forks Script
        run: |
          python main.py "${{ github.event.inputs.github_token }}" "${{ github.event.inputs.username }}"
